### ISSUE TITLE
[Error]  Players cannot be punished anymore when using ATAC

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#868]
seems that since https://github.com/s1lentq/ReGameDLL_CS/commit/108db28143af69bbbf47671f1ecaf173d5edd618  the amxmodx plugin [ATAC](https://forums.alliedmods.net/showthread.php?t=61572)  doesnt recognize teamattacks/teamkills  anymore, thus players cannot be punished.

**Comment by wopox1337** [comment]
Should be fixed by https://github.com/s1lentq/ReGameDLL_CS/commit/1e49d947927e7f6f2fd70d8398e4a9519a34450a

**Comment by fred0r** [comment]
thx - will check asap

**Comment by s1lentq** [comment]
@fred0r 

This is still not fixed.
The ATAC plugin registers events with the `'a'` flag only (MSG_ALL/MSG_BROADCAST).
`"a" - Global event (sent to every client without exceptions)`.
But now, ReGameDLL_CS sends DeathMsg individually with various conditions to each client (MSG_ONE). Consequently, the ATAC plugin needs to account for the `"b" - flag, which signifies an event sent to a single client`.

I don't have any ideas on how to fix this on the ReGameDLL_CS side because it doesn't appear to be a ReGameDLL_CS bug. Instead, it seems to be a flaw in the ATAC plugin itself, as it doesn't want to handle all DeathMsg events.

**Comment by fred0r** [comment]
@s1lentq 
so changing `register_event( "DeathMsg", "Event_DeathMsg", "a", "1>0" )` to `register_event( "DeathMsg", "Event_DeathMsg", "b", "1>0" )` in _atac.sma_ will fix this behaviour?

**Comment by s1lentq** [comment]
> @s1lentq so changing `register_event( "DeathMsg", "Event_DeathMsg", "a", "1>0" )` to `register_event( "DeathMsg", "Event_DeathMsg", "b", "1>0" )` in _atac.sma_ will fix this behaviour?

better use both flags, `ba`

**Comment by fred0r** [comment]
noice - thx!

**Comment by fred0r** [comment]
offtopic:
now in understand why you seem to prefer a 'general approach', since this new behaviour might affect a lot more amxx-plugins.
e.g. [PTB](https://forums.alliedmods.net/showthread.php?p=227369):
`register_event("DeathMsg","death_msg","a")`

**Comment by s1lentq** [comment]
@fred0r 
Yep, it seems there are many plugins like this, it's sad. My hands are tied, and I have no choice but to revert the new behavior in the code.

**Comment by justgo97** [comment]
> @fred0r Yep, it seems there are many plugins like this, it's sad. I have no choice but to revert the new behavior in the code

Maybe it can be edited so that MSG_ALL is used again but remove the death origin option since it's the only one that can be abused? For the rest sending to all players is okay.

**Comment by fred0r** [comment]
since it seems to be fixed now...
